name: Run Jest unit tests

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        
jobs:
    build:
        runs-on: ubuntu-latest
        container: node:20

        steps:
        - run: npm ci
    tests:
        runs-on: ubuntu-latest
        steps:
        - run: npm test
